# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run: |
          name: Install Docker client
          command: |
          docker build -t quay.io/vguar/hello-go:latest .     
          #echo ${HELLO_TOKEN} | docker login -u "vguar+helloworld" --password-stdin quay.io

  #    - run:
  #      name: Build application Docker image
  #      command: |
  #          docker build --cache-from=app -t app .
  #    - deploy:
  #      name: Push application Docker image
  #      command: |
  #          echo ${HELLO_TOKEN} | docker login -u "vguar+helloworld" --password-stdin quay.io
  #          docker tag app:latest quay.io/vguar/hello-go:latest
  #          docker push quay.io/vguar/hello-go:latest