---
version: 2.1

executors:
  # Whenever the Go version is updated here, .promu.yml should also be updated.
  golang:
    docker:
    - image: circleci/golang:1.11

jobs:
  build:
    
    machine: true
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}

  docker_hub_master:
    executor: golang

    steps:
      - checkout
      - setup_remote_docker:
      - run:
          name: Build application Docker image
          command: |
            docker login -u "vguar+helloworld" -p ${HELLO_TOKEN} quay.io
            docker build -t quay.io/vguar/hello-go:latest .
            docker push quay.io/vguar/hello-go:latest
               

  #    - run:
  #      name: Build application Docker image
  #      command: |
  #          docker build --cache-from=app -t app .
  #    - deploy:
  #      name: Push application Docker image
  #      command: |
  #          echo ${HELLO_TOKEN} | docker login -u "vguar+helloworld" --password-stdin quay.io
  #          docker tag app:latest quay.io/vguar/hello-go:latest
  #          docker push quay.io/vguar/hello-go:latest