---
version: 2.1

jobs:
  build:
    machine:
      # Cache docker layers so that we strongly speed up this job execution
      docker_layer_caching: true
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run:
          name: Build application Docker image
          command: |
            docker login -u "vguar+helloworld" -p ${HELLO_TOKEN} quay.io
            docker build -t quay.io/vguar/hello-go:latest .
            docker push quay.io/vguar/hello-go:latest
               

  #    - run:
  #      name: Build application Docker image
  #      command: |
  #          docker build --cache-from=app -t app .
  #    - deploy:
  #      name: Push application Docker image
  #      command: |
  #          echo ${HELLO_TOKEN} | docker login -u "vguar+helloworld" --password-stdin quay.io
  #          docker tag app:latest quay.io/vguar/hello-go:latest
  #          docker push quay.io/vguar/hello-go:latest